-- SQL Operations
-- SQL Keyed-In order (the sequence in which SQL words must be followed to avoid error)
/*
-- 1. SELECT: Must be follwed by list of column or derived column
-- SELECT ID, FNAME, LNAME, COUNT(ID)

-- 2. FROM: DATA MUST ALWAYS BE SELECTED FROM A TABLE 
-- EXAMPLE: FROM ANOTHERTABLE

3. WHERE: ALLOWS US TO NARROW DOWN OR FILTER OUTPUT OF OUR SELECT STATEMENT
-- EXAMPLE: WHERE ID = 1

4. GROUP BY: IS USED TO GROUP THE OUTCOME OF SELECT STATEMENT WHENEVER WE HAVE COLUMNS AND AGGREGATED DERIVED 
-- COLUMNS OR NON-AGGREGATED DERIVED COLUMNS, THEN, WE USE 
-- GROUP BY THE COLUMN(S) AND NON AGGREGATED DERIVED COLUMNS.
-- EXAMPLE: GROUP BY ID

5. HAVING: USE TO FILTER ONLY ON AGGREGATED COLUMN(S)
-- EXAMPLE: HAVING SUM(SALES) > 100000

6. ORDER BY: USE TO SORT THE OUTPUT OF SELECT STATEMENT
-- THE DEFAULT ORDER IS ASCENDING
-- EXAMPLE: ORDER BY SUM(SALES) DESC

-- LOGICAL PROCESSING ORDER
-- FROM (SQL WON'T UNDERSTAND THE COMMAND SELECT UNTIL FROM STATEMENT IS WRITTEN, D/4 SQL FOLLOW THIS LOGICAL ORDER)

-- FROM
-- WHERE
-- GROUP BY
-- HAVING
-- SELECT
-- ORDER BY
*/
-- SQL OPERATORS
-- ARITHMETIC OPERATIONS (+, -, *, /, %)
SELECT 1 + 1 AS ADDITION, 2-1 AS SUBTRACTION,
30/3 AS DIVISION, 2*5 AS MULTIPLICATION,
35 % 6AS REMAINDER;

-- COMPARISON OPERATOR(=, >, <, >=, <=, <>)

-- LOGICAL OPERATOR (AND, OR, BETWEEN, IN, LIKE, NOT)
-- AND
SELECT ID, FNAME
FROM DBO.sampleTable
WHERE ID > 1 AND ID < 3;
-- OR 

-- LIKE (IS USED WITH THE WILDCARD SYMBOLS: %, _, [],^,)
/*
-- LIKE OPERATOR DESCRIPTION
WHERE CUSTOMERNAME LIKE 'a%'	Finds any values that start with "a"
WHERE CUSTOMERNAME LIKE '%a'	Finds any values that end with "a"
WHERE CUSTOMERNAME LIKE '%or'	Finds any values that have "or" in any position
WHERE CUSTOMERNAME LIKE '_r%'	Finds any values that have "r" in the second position	
WHERE CUSTOMERNAME LIKE 'a_%'	Finds any values that start with "a" and are at least 2 characters in length
WHERE CUSTOMERNAME LIKE 'a__%'	Finds any values that start with "a" and are at least 3 characters in length
WHERE CUSTOMERNAME LIKE 'a%o'	Finds any values that start with "a" and ends with "o"